In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [17]:
df = pd.read_excel('../data/cpi_indicators_for_forecast.xlsx')
df.head()

,Date,Base Rate (%),Export,Import,M2,observation_date,POILBREUSDM,usdt_kzt,cpi_total,food,non_food,paid_services
0,2022-01-01,9.75,6093.9,2847.3,23424245,2022-01-01,85.622381,433.66,100.7,101.0,100.3,100.6
1,2022-02-01,10.25,6068.5,3427.0,23868588,2022-02-01,94.267000,434.44,101.5,102.2,100.8,101.2
2,2022-03-01,13.50,6976.8,3579.2,23388580,2022-03-01,112.440000,497.18,105.2,108.2,103.6,102.6
3,2022-04-01,13.50,7405.8,3842.6,23174386,2022-04-01,106.155714,453.32,107.3,111.6,104.9,103.6
4,2022-05-01,14.00,7718.6,4038.8,22903738,2022-05-01,112.113636,430.71,108.8,113.5,106.3,104.5

In [30]:
df_clean = df.dropna(axis=0).reset_index(drop=True)

In [31]:
df_clean.tail()

,Date,Base Rate (%),Export,Import,M2,observation_date,POILBREUSDM,usdt_kzt,cpi_total,food,non_food,paid_services
42,2025-07-01,16.5,6754.5,5466.9,40746378,2025-07-01,67.12,528.81,107.7,108.4,105.3,109.2
43,2025-08-01,16.5,6435.3,5312.0,41091093,2025-08-01,67.90,538.95,108.8,108.9,106.4,110.8
44,2025-09-01,16.5,7301.3,5731.1,41626870,2025-09-01,67.40,540.74,110.0,109.9,108.0,111.9
45,2025-10-01,16.5,7100.9,5826.5,42462331,2025-10-01,63.90,539.92,110.5,111.0,109.3,111.0
46,2025-11-01,18.0,6562.6,5823.2,42192683,2025-11-01,63.60,522.72,111.4,112.2,110.3,111.4